print("Hello, welcome to your first program!")
print("Click run to see what this program does.")
print("Isaiah Greenway")
print("I do not have a favorite muscian")
print(" I would love to go to bora bora")
print(" i like to watch television")
print("7/14/20")